apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: drunk-guanaco-go 
  janus-idp.io/tekton: drunk-guanaco-go
  backstage.io/kubernetes-id: drunk-guanaco-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: drunk-guanaco-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  